"""
agent_detector.py
=================
Universal CV-based detector for multi-agent polygon environments.

Works with ANY color scheme generated by the polygon tool — does NOT
rely on hardcoded HSV ranges.  Instead it:
  1. Finds the map bounding box inside preview.png
  2. Clusters all saturated colored pixels into N blobs (one per agent)
  3. Separates agents (circles) from P/D markers (small squares) by shape
  4. Detects P/D markers (pickup / dropoff) for MAPD scenarios
  5. Falls back to scenario.json ground-truth when CV detection fails
"""

import cv2
import numpy as np
import json
from typing import List, Dict, Tuple, Optional


# ── helpers ───────────────────────────────────────────────────────────────────

def find_map_region(img: np.ndarray) -> Tuple[int, int, int, int]:
    """
    Locate the map bounding box inside preview.png.
    The map is surrounded by a thick black border — we find the largest
    rectangular contour on a dark-thresholded image.

    Returns (x_min, y_min, x_max, y_max) in pixel coordinates.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, thresh = cv2.threshold(gray, 30, 255, cv2.THRESH_BINARY_INV)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        h, w = img.shape[:2]
        return (0, 0, w, h)
    largest = max(contours, key=cv2.contourArea)
    x, y, w, h = cv2.boundingRect(largest)
    margin = 5
    return (x + margin, y + margin, x + w - margin, y + h - margin)


def pixel_to_grid(px: float, py: float,
                  map_region: Tuple[int, int, int, int],
                  grid_w: int, grid_h: int) -> Tuple[int, int]:
    """Convert pixel coordinates inside preview.png → grid cell (gx, gy)."""
    x_min, y_min, x_max, y_max = map_region
    nx = (px - x_min) / max(1, x_max - x_min)
    ny = (py - y_min) / max(1, y_max - y_min)
    gx = int(np.clip(nx * grid_w, 0, grid_w - 1))
    gy = int(np.clip(ny * grid_h, 0, grid_h - 1))
    return gx, gy


def _saturation_mask(hsv: np.ndarray,
                     sat_min: int = 80,
                     val_min: int = 60) -> np.ndarray:
    """
    Binary mask of all saturated (coloured) pixels.
    Excludes near-white, near-black, and near-grey regions.
    """
    return cv2.inRange(hsv,
                       np.array([0,   sat_min, val_min]),
                       np.array([180, 255,     255]))


def _dominant_hue(hsv_patch: np.ndarray, mask: np.ndarray) -> float:
    """Mean hue of masked pixels (circular mean to handle red wrap-around)."""
    hues = hsv_patch[:, :, 0][mask > 0].astype(np.float32)
    if len(hues) == 0:
        return 0.0
    # Circular mean (OpenCV H is 0-180, so wrap at 180)
    angles = hues * 2.0  # convert to 0-360
    sin_mean = np.mean(np.sin(np.radians(angles)))
    cos_mean = np.mean(np.cos(np.radians(angles)))
    mean_angle = np.degrees(np.arctan2(sin_mean, cos_mean)) % 360
    return mean_angle / 2.0  # back to 0-180


# ── main blob detector ────────────────────────────────────────────────────────

def _extract_blobs(img: np.ndarray,
                   map_region: Tuple[int, int, int, int],
                   min_area: int = 80
                   ) -> List[Dict]:
    """
    Find ALL coloured blobs inside the map region.
    Returns list of dicts with keys:
        pixel, area, circularity, hue, contour
    Sorted by area descending.
    """
    x_min, y_min, x_max, y_max = map_region
    roi = img[y_min:y_max, x_min:x_max]
    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)

    sat_mask = _saturation_mask(hsv)

    # Morphological cleanup
    kernel = np.ones((4, 4), np.uint8)
    sat_mask = cv2.morphologyEx(sat_mask, cv2.MORPH_OPEN,  kernel)
    sat_mask = cv2.morphologyEx(sat_mask, cv2.MORPH_CLOSE, kernel)

    contours, _ = cv2.findContours(sat_mask, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    blobs = []
    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area < min_area:
            continue
        perim = cv2.arcLength(cnt, True)
        circ  = (4 * np.pi * area / perim ** 2) if perim > 0 else 0.0
        M     = cv2.moments(cnt)
        if M["m00"] == 0:
            continue
        cx = M["m10"] / M["m00"]
        cy = M["m01"] / M["m00"]

        # Hue of this blob
        blob_mask = np.zeros(sat_mask.shape, np.uint8)
        cv2.drawContours(blob_mask, [cnt], -1, 255, -1)
        hue = _dominant_hue(hsv, blob_mask)

        blobs.append({
            "pixel":       (cx + x_min, cy + y_min),  # back to full image coords
            "area":        area,
            "circularity": circ,
            "hue":         hue,
            "contour":     cnt,
        })

    blobs.sort(key=lambda b: b["area"], reverse=True)
    return blobs


def _hue_distance(h1: float, h2: float) -> float:
    """Circular distance between two hues (0-180)."""
    d = abs(h1 - h2)
    return min(d, 180 - d)


def _assign_blobs_to_agents(blobs: List[Dict],
                             num_agents: int,
                             circularity_threshold: float = 0.45
                             ) -> Tuple[List[Dict], List[Dict]]:
    """
    Split blobs into agent blobs (circles) and marker blobs (P/D squares).

    Strategy:
      - Agents are the N most circular large blobs.
      - Everything else is a potential P/D marker (less circular, smaller).

    Returns (agent_blobs, marker_blobs).
    """
    # Sort by circularity * area (prefer round AND large)
    scored = sorted(blobs,
                    key=lambda b: b["circularity"] * b["area"],
                    reverse=True)

    agent_blobs  = [b for b in scored if b["circularity"] >= circularity_threshold]
    marker_blobs = [b for b in blobs  if b["circularity"] <  circularity_threshold]

    # If we have more circular blobs than agents, keep only the N best
    agent_blobs = agent_blobs[:num_agents]

    return agent_blobs, marker_blobs


def _match_agents_to_blobs(agent_blobs: List[Dict],
                            agents_data: List[Dict],
                            map_region: Tuple[int, int, int, int],
                            grid_w: int, grid_h: int
                            ) -> List[Dict]:
    """
    Match detected blobs to agent IDs using hue similarity to the
    expected matplotlib tab10 palette, falling back to spatial proximity
    to ground-truth start positions when hue is ambiguous.

    Tab10 hues (OpenCV 0-180):
      blue=113, orange=15, green=63, red=0/175, purple=138,
      brown=14, pink=160, gray=0(low-sat), olive=30, cyan=91
    """
    TAB10_HUES = [113, 15, 63, 0, 138, 14, 160, 90, 30, 91]

    results = []
    used_blob_indices = set()

    for i, a in enumerate(agents_data):
        expected_hue = TAB10_HUES[i % len(TAB10_HUES)]
        best_idx  = None
        best_dist = 1e9

        for j, blob in enumerate(agent_blobs):
            if j in used_blob_indices:
                continue
            dist = _hue_distance(blob["hue"], expected_hue)
            if dist < best_dist:
                best_dist = dist
                best_idx  = j

        if best_idx is not None and best_dist < 40:
            blob = agent_blobs[best_idx]
            used_blob_indices.add(best_idx)
            px, py = blob["pixel"]
            gx, gy = pixel_to_grid(px, py, map_region, grid_w, grid_h)
            results.append({
                "id":     a["id"],
                "pixel":  (int(px), int(py)),
                "grid":   (gx, gy),
                "hue":    blob["hue"],
                "found":  True,
            })
        else:
            # Fallback: use ground-truth start from scenario.json
            start = a["start"]
            results.append({
                "id":    a["id"],
                "pixel": None,
                "grid":  (start[0], start[1]),
                "hue":   None,
                "found": False,
            })

    return results


# ── P/D marker detection ──────────────────────────────────────────────────────

def detect_markers(preview_path: str,
                   scenario_path: str,
                   grid_w: int, grid_h: int
                   ) -> List[Dict]:
    """
    Detect pickup (P) and dropoff (D) markers for MAPD scenarios.

    Markers are small coloured squares on the map.  We use the same
    blob pipeline but select the LESS circular blobs and match them
    to tasks from tasks.json via ground-truth grid positions.

    Returns list of dicts:
      {"id": "task_1", "type": "pickup"|"dropoff",
       "pixel": (px,py), "grid": (gx,gy), "found": bool}
    """
    import os
    base = os.path.dirname(scenario_path)
    tasks_path = os.path.join(base, "tasks.json")

    if not os.path.exists(tasks_path):
        return []

    with open(tasks_path) as f:
        tasks = json.load(f)
    if not tasks:
        return []

    img = cv2.imread(preview_path)
    if img is None:
        return []

    map_region = find_map_region(img)
    blobs = _extract_blobs(img, map_region, min_area=30)

    # Markers are small, less circular blobs
    marker_blobs = [b for b in blobs if b["circularity"] < 0.55]

    results = []
    for task in tasks:
        for marker_type in ("pickup", "dropoff"):
            gt = task[marker_type]  # ground-truth grid cell
            # Find nearest marker blob to this ground-truth position
            best_blob = None
            best_dist = 1e9
            for b in marker_blobs:
                px, py = b["pixel"]
                gx, gy = pixel_to_grid(px, py, map_region, grid_w, grid_h)
                d = abs(gx - gt[0]) + abs(gy - gt[1])
                if d < best_dist:
                    best_dist = d
                    best_blob = b

            if best_blob is not None and best_dist <= 3:
                px, py = best_blob["pixel"]
                gx, gy = pixel_to_grid(px, py, map_region, grid_w, grid_h)
                results.append({
                    "id":     task["id"],
                    "type":   marker_type,
                    "pixel":  (int(px), int(py)),
                    "grid":   (gx, gy),
                    "found":  True,
                })
            else:
                # Fallback to ground truth
                results.append({
                    "id":    task["id"],
                    "type":  marker_type,
                    "pixel": None,
                    "grid":  (gt[0], gt[1]),
                    "found": False,
                })

    return results


# ── public API ────────────────────────────────────────────────────────────────

def detect_agents(preview_path: str,
                  scenario_path: str,
                  grid_w: int, grid_h: int) -> List[Dict]:
    """
    Main function: detect all agents in preview.png.

    Works universally — does not rely on hardcoded colors.
    Falls back to scenario.json ground truth for undetected agents.

    Returns list of dicts:
      {"id", "pixel", "grid", "hue", "found"}
    """
    img = cv2.imread(preview_path)
    if img is None:
        raise FileNotFoundError(f"Cannot open: {preview_path}")

    with open(scenario_path) as f:
        scenario = json.load(f)

    num_agents  = scenario["num_agents"]
    agents_data = scenario["agents"]

    map_region  = find_map_region(img)
    blobs       = _extract_blobs(img, map_region)
    agent_blobs, _ = _assign_blobs_to_agents(blobs, num_agents)
    results     = _match_agents_to_blobs(
        agent_blobs, agents_data, map_region, grid_w, grid_h)

    return results


def print_detection_results(results: List[Dict]) -> None:
    """Pretty-print detection results."""
    print("=" * 55)
    print("AGENT DETECTION RESULTS")
    print("=" * 55)
    for r in results:
        status = "✓ CV  " if r["found"] else "✗ JSON"
        hue_str = f"hue={r['hue']:.0f}" if r["hue"] is not None else "hue=n/a"
        print(f"  {status}  {r['id']:12s}  {hue_str:10s}  grid={r['grid']}")
    found = sum(1 for r in results if r["found"])
    print(f"\nDetected visually: {found}/{len(results)}")
    print("=" * 55)


# ── module self-test ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, ".")
    from map_parser import load_grid_cell_resolution

    # Auto-discover cases
    data_dir = "data"
    cases = sorted([
        d for d in os.listdir(data_dir)
        if os.path.isdir(os.path.join(data_dir, d))
    ]) if os.path.exists(data_dir) else []

    if not cases:
        print("No cases found in data/")
        sys.exit(1)

    print(f"Found {len(cases)} case(s): {cases}\n")

    for case in cases:
        base          = f"{data_dir}/{case}"
        preview_path  = f"{base}/preview.png"
        scenario_path = f"{base}/scenario.json"
        map_path      = f"{base}/map.png"
        metrics_path  = f"{base}/metrics.json"

        if not all(os.path.exists(p) for p in
                   [preview_path, scenario_path, map_path, metrics_path]):
            print(f"[SKIP] {case} — missing files")
            continue

        print(f"── {case} ──")
        grid, gw, gh = load_grid_cell_resolution(map_path, metrics_path)
        results = detect_agents(preview_path, scenario_path, gw, gh)
        print_detection_results(results)

        # MAPD: also detect P/D markers
        with open(scenario_path) as f:
            sc = json.load(f)
        if sc.get("type") == "mapd":
            markers = detect_markers(preview_path, scenario_path, gw, gh)
            found_m = sum(1 for m in markers if m["found"])
            print(f"  P/D markers detected: {found_m}/{len(markers)}")
        print()